setwd("./R/Course Project 1/")
a <- read.table('household_power_consumption.txt',header = TRUE,sep = ";",stringsAsFactors = FALSE, dec = ".")
dataset <- a[a$Date %in% c("1/2/2007","2/2/2007"),]
dataset$Date <- as.Date(dataset$Date,format = "%d/%m/%Y")
dataset$Time <- strptime(paste(dataset$Date, dataset$Time,sep = " "),format = "%Y-%m-%d %H:%M:%S")
dataset$Global_active_power<-as.numeric(dataset$Global_active_power)                  
dataset$Sub_metering_1 <-as.numeric(dataset$Sub_metering_1)
dataset$Sub_metering_2 <-as.numeric(dataset$Sub_metering_2)
dataset$Sub_metering_3 <-as.numeric(dataset$Sub_metering_3)
png("plot3.png",width = 480, height = 480)
plot(dataset$Time,dataset$Sub_metering_1,type = "l",ylab = "Energy sub metering",xlab = "")
lines(dataset$Time,dataset$Sub_metering_2,type = "l",col="red")
lines(dataset$Time,dataset$Sub_metering_3,type = "l",col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = 1,lwd=2.5,col=c("black","red","blue"))
dev.off()